version: '3.1'

services:
  stream-deck-app:
    container_name: stream-deck-app
    image: postgres:14.1-alpine
    ports:
      - '7777:8080'

    build:
      context: .
      dockerfile: invest_service/Dockerfile
    environment:
      TEST: test
    restart: always